version: "3.2"
services:
  app-demo:
    image: komunitin/komunitin-app:demo
    restart: unless-stopped
    ports:
      - "12030:80"

  notifications:
    depends_on:
      - redis
    image: komunitin/komunitin-notifications:latest
    ports:
      - "12028:2028"

  redis:
    image: redis:7

